In [1]:
import numpy as np
from keras.datasets import mnist
from keras.models import Sequential 
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras import Model
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.utils import to_categorical
from skimage.transform import resize
import h5py
import os


In [2]:
# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Resize images to 42x42
x_train_resized = np.zeros((x_train.shape[0], 42, 42))
for i in range(x_train.shape[0]):
    x_train_resized[i] = resize(x_train[i], (42, 42))

x_test_resized = np.zeros((x_test.shape[0], 42, 42))
for i in range(x_test.shape[0]):
    x_test_resized[i] = resize(x_test[i], (42, 42))

# Reshape to add channel dimension (required for Keras)
x_train_resized = x_train_resized.reshape(-1, 42, 42, 1)
x_test_resized = x_test_resized.reshape(-1, 42, 42, 1)

# Normalize pixel values to range [0, 1]
x_train_resized = x_train_resized.astype('float32') / 255.0
x_test_resized = x_test_resized.astype('float32') / 255.0

# One-hot encode labels
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)


In [3]:
# import numpy as np
# from keras.models import Sequential
# from keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
# from keras.callbacks import ModelCheckpoint

# model = Sequential()
# model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=(42, 42, 1)))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Conv2D(4, kernel_size=(3, 3), activation='relu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))
# model.add(Flatten())
# model.add(Dropout(0.5))
# model.add(Dense(10, activation='softmax'))

# # Compile the model
# model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# # Train the model (Replace X_train and y_train with your training data)
# model.fit(x_train_resized, y_train, batch_size=50, epochs=15, validation_data=(x_test_resized, y_test))

# # Save the model's weights and biases
# model.save('model_weights.h5')


In [4]:
# from keras.models import load_model

# # Load the model from the .h5 file
# model = load_model('model_weights.h5')

# # Get the weights for each layer
# weights = model.get_weights()

# # Save the weights to a text file
# with open('model_weights.txt', 'w') as file:
#     for layer_weights in weights:
#         for weight in layer_weights.flatten():
#             file.write(str(weight) + '\n')

# print("Model weights saved to model_weights.txt")

In [5]:
# model.summary()

In [6]:
import numpy as np
from keras.models import Sequential, load_model
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dropout, Dense
from keras.callbacks import ModelCheckpoint


model = load_model('model_weights.h5')

# Evaluate the model on the test set
loss, accuracy = model.evaluate(x_test_resized, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 885us/step - accuracy: 0.9181 - loss: 0.2984
Test Loss: 0.2572062909603119
Test Accuracy: 0.9316999912261963


In [7]:
from keras.preprocessing import image
import numpy as np

# Load and preprocess the single image
img_path = 'demo7.png'  
img = image.load_img(img_path, target_size=(42, 42), color_mode='grayscale')  
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
# img_array /= 255.  # Normalize the pixel values

# Predict the output of the model for the single image
predictions = model.predict(img_array)

# Print the predicted class probabilities
print("Predicted class probabilities:", predictions)

# Get the predicted class label
predicted_class = np.argmax(predictions)
print("Predicted class label:", predicted_class)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Predicted class probabilities: [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
Predicted class label: 3


# Conv1

In [8]:
weights_and_biases = np.loadtxt("model_weights.txt")

weights_shape = (3, 3, 1, 4)  # Assuming kernel size of (3, 3) and 4 filters

weights = weights_and_biases[0:36].reshape(weights_shape)  # weights
biases = weights_and_biases[36:40]  # biases


#Model Below
model = Sequential()
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=(42, 42, 1)))

model.layers[0].set_weights([weights, biases])



img_path = 'demo7.png'  
img = image.load_img(img_path, target_size=(42, 42), color_mode='grayscale')  
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
# img_array /= 255.  
img_flat = img_array.flatten()
img_array = np.array(img_flat)


img_array = img_flat.reshape((1, 42, 42, 1))  # Reshape to (batch_size, height, width, channels)

conv1_output = model.predict(img_array)

print("Output shape of the first convolutional layer:", conv1_output.shape)

# Save the convolutional layer output
with open('Python_prog_out_conv.txt', 'w') as file:
    for c in range(conv1_output.shape[3]):  
        file.write("Channel %d:\n" % (c + 1))

        for i in range(conv1_output.shape[1]):  
            for j in range(conv1_output.shape[2]):  
                file.write("%0.2f" % conv1_output[0, i, j, c])
                if j != conv1_output.shape[2] - 1:
                    file.write(", ")
            file.write("\n")

        file.write("\n")

print("Convolutional layer output saved")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Output shape of the first convolutional layer: (1, 40, 40, 4)
Convolutional layer output saved


c:\Users\Rishit Thakkar\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


# Max1

In [9]:
weights_and_biases = np.loadtxt("model_weights.txt")

weights_shape = (3, 3, 1, 4)  # Assuming kernel size of (3, 3) and 4 filters

weights = weights_and_biases[0:36].reshape(weights_shape)  # weights
biases = weights_and_biases[36:40]  # biases


#Model Below
model = Sequential()
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=(42, 42, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.layers[0].set_weights([weights, biases])



img_path = 'demo7.png'  
img = image.load_img(img_path, target_size=(42, 42), color_mode='grayscale')  
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
# img_array /= 255.  
img_flat = img_array.flatten()
img_array = np.array(img_flat)


img_array = img_flat.reshape((1, 42, 42, 1))  # Reshape to (batch_size, height, width, channels)

conv1_output = model.predict(img_array)

print("Output shape of the first Max Pool layer:", conv1_output.shape)

# Save the convolutional layer output
with open('Python_prog_out_Max1.txt', 'w') as file:
    for c in range(conv1_output.shape[3]):  
        file.write("Channel %d:\n" % (c + 1))

        for i in range(conv1_output.shape[1]):  
            for j in range(conv1_output.shape[2]):  
                file.write("%0.2f" % conv1_output[0, i, j, c])
                if j != conv1_output.shape[2] - 1:
                    file.write(", ")
            file.write("\n")

        file.write("\n")

print("Max 1 layer output saved")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Output shape of the first Max Pool layer: (1, 20, 20, 4)
Max 1 layer output saved


# Conv 2

In [10]:
weights_and_biases = np.loadtxt("model_weights.txt")

weights_shape = (3, 3, 1, 4)  # Assuming kernel size of (3, 3) and 4 filters
weights2_shape = (3, 3, 4, 4)

weights = weights_and_biases[0:36].reshape(weights_shape)  # weights
biases = weights_and_biases[36:40]  # biases

weights2 = weights_and_biases[40:184].reshape(weights2_shape)
biases2 = weights_and_biases[184:188]

#Model Below
model = Sequential()
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=(42, 42, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu'))

model.layers[0].set_weights([weights, biases])
model.layers[2].set_weights([weights2, biases2])



img_path = 'demo7.png'  
img = image.load_img(img_path, target_size=(42, 42), color_mode='grayscale')  
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
# img_array /= 255.  
img_flat = img_array.flatten()
img_array = np.array(img_flat)


img_array = img_flat.reshape((1, 42, 42, 1))  # Reshape to (batch_size, height, width, channels)

conv1_output = model.predict(img_array)

print("Output shape of the first convolutional layer:", conv1_output.shape)

# Save the convolutional layer output
with open('Python_prog_out_conv2.txt', 'w') as file:
    for c in range(conv1_output.shape[3]):  
        file.write("Channel %d:\n" % (c + 1))

        for i in range(conv1_output.shape[1]):  
            for j in range(conv1_output.shape[2]):  
                file.write("%0.2f" % conv1_output[0, i, j, c])
                if j != conv1_output.shape[2] - 1:
                    file.write(", ")
            file.write("\n")

        file.write("\n")

print("Convolutional layer output saved")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Output shape of the first convolutional layer: (1, 18, 18, 4)
Convolutional layer output saved


# Max 2

In [12]:
weights_and_biases = np.loadtxt("model_weights.txt")

weights_shape = (3, 3, 1, 4)  # Assuming kernel size of (3, 3) and 4 filters
weights2_shape = (3, 3, 4, 4)

weights = weights_and_biases[0:36].reshape(weights_shape)  # weights
biases = weights_and_biases[36:40]  # biases

weights2 = weights_and_biases[40:184].reshape(weights2_shape)
biases2 = weights_and_biases[184:188]

#Model Below
model = Sequential()
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=(42, 42, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))

model.layers[0].set_weights([weights, biases])
model.layers[2].set_weights([weights2, biases2])



img_path = 'demo7.png'  
img = image.load_img(img_path, target_size=(42, 42), color_mode='grayscale')  
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
# img_array /= 255.  
img_flat = img_array.flatten()
img_array = np.array(img_flat)


img_array = img_flat.reshape((1, 42, 42, 1))  # Reshape to (batch_size, height, width, channels)

conv1_output = model.predict(img_array)

print("Output shape of the 2nd MaxPool layer:", conv1_output.shape)

# Save the convolutional layer output
with open('Python_prog_out_max2.txt', 'w') as file:
    for c in range(conv1_output.shape[3]):  
        file.write("Channel %d:\n" % (c + 1))

        for i in range(conv1_output.shape[1]):  
            for j in range(conv1_output.shape[2]):  
                file.write("%0.2f" % conv1_output[0, i, j, c])
                if j != conv1_output.shape[2] - 1:
                    file.write(", ")
            file.write("\n")

        file.write("\n")

print("Maxpool layer 2 output saved")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Output shape of the 2nd MaxPool layer: (1, 9, 9, 4)
Maxpool layer 2 output saved


# Flatten

In [17]:
weights_and_biases = np.loadtxt("model_weights.txt")

weights_shape = (3, 3, 1, 4)  # Assuming kernel size of (3, 3) and 4 filters
weights2_shape = (3, 3, 4, 4)
weights3_shape = (324, 10)

weights = weights_and_biases[0:36].reshape(weights_shape)  # weights
biases = weights_and_biases[36:40]  # biases

weights2 = weights_and_biases[40:184].reshape(weights2_shape)
biases2 = weights_and_biases[184:188]




#Model Below
model = Sequential()
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=(42, 42, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))
model.add(Flatten())


model.layers[0].set_weights([weights, biases])
model.layers[2].set_weights([weights2, biases2])


img_path = 'demo7.png'  
img = image.load_img(img_path, target_size=(42, 42), color_mode='grayscale')  
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
# img_array /= 255.  
img_flat = img_array.flatten()
img_array = np.array(img_flat)


img_array = img_flat.reshape((1, 42, 42, 1))  # Reshape to (batch_size, height, width, channels)

conv1_output = model.predict(img_array)

# Save the convolutional layer output
print("Output shape of the Flatten layer:", conv1_output.shape)

# Save the flatten layer output
with open('Python_prog_out_Flatten.txt', 'w') as file:
    for i in range(conv1_output.shape[1]):
        file.write("Neuron %d: %0.2f\n" % (i + 1, conv1_output[0, i]))

print("Flatten layer output saved")


[[[[-2.64759470e+00  9.48329200e-01  7.22843000e-01 -1.82670260e+00]
   [ 6.09292540e-02 -1.44774630e-01 -2.15200110e-01  1.98423040e-02]
   [ 2.03331220e-01  4.21472300e-02  4.69026800e-02  2.53995200e-01]
   [-2.58511730e+00  6.44776460e-01  3.96601800e-01 -2.26895020e+00]]

  [[-3.45524290e+00  5.41710400e-01  2.00895790e+00 -7.16897100e-01]
   [ 1.54876710e-01 -2.45558540e-01 -8.68982500e-02  2.87901700e-02]
   [ 5.68736200e-02  1.44750570e-01 -2.13798760e-01  2.59440100e-01]
   [-3.34199260e+00  8.65652600e-01  2.02273600e+00 -9.24704600e-01]]

  [[-3.55474800e+00 -1.16067660e+00  4.85305250e-01  2.68154050e-01]
   [-1.43806470e-01 -1.55931560e-01  2.00733060e-02 -1.84719740e-01]
   [ 1.84435000e-01 -2.25904830e-02 -2.39373030e-01  1.54186190e-01]
   [-3.78928350e+00 -8.91361830e-01  9.41256170e-01 -1.42298770e-01]]]


 [[[ 7.29974200e-01  9.42887500e-01  1.03263510e+00  3.61674820e-01]
   [-1.54911230e-02  1.23387866e-01 -3.20493130e-02  2.20656650e-01]
   [ 2.28943270e-01  2.058

c:\Users\Rishit Thakkar\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


# Flatten and Dense

In [31]:
weights_and_biases = np.loadtxt("model_weights.txt")

weights_shape = (3, 3, 1, 4)  # Assuming kernel size of (3, 3) and 4 filters
weights2_shape = (3, 3, 4, 4)
weights3_shape = (324, 10)

weights = weights_and_biases[0:36].reshape(weights_shape)  # weights
biases = weights_and_biases[36:40]  # biases

weights2 = weights_and_biases[40:184].reshape(weights2_shape)
biases2 = weights_and_biases[184:188]

weights3 = weights_and_biases[188:3428].reshape(weights3_shape)
biases3 = weights_and_biases[3428:3438]

print(weights3)
print(weights3.shape)

#Model Below
model = Sequential()
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=(42, 42, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))
model.add(Flatten())
model.add(Dense(10, activation='relu'))

model.layers[0].set_weights([weights, biases])
model.layers[2].set_weights([weights2, biases2])
model.layers[5].set_weights([weights3, biases3])


img_path = 'demo7.png'  
img = image.load_img(img_path, target_size=(42, 42), color_mode='grayscale')  
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
# img_array /= 255.  
img_flat = img_array.flatten()
img_array = np.array(img_flat)


img_array = img_flat.reshape((1, 42, 42, 1))  # Reshape to (batch_size, height, width, channels)

conv1_output = model.predict(img_array)

# Save the convolutional layer output
print("Output shape of the Dense layer:", conv1_output.shape)

# Save the dense layer output
with open('Python_prog_out_Dense.txt', 'w') as file:
    for i in range(conv1_output.shape[1]):
        file.write("Neuron %d: %0.2f\n" % (i + 1, conv1_output[0, i]))

print("Dense layer output saved")


[[-0.0628828   0.08443162 -0.06693464 ... -0.16860108 -0.2712759
  -0.5382995 ]
 [-0.56143224  0.04709087 -0.01200746 ... -0.04370009 -0.51703787
   0.00160865]
 [-0.05777652  0.05571867 -0.13674326 ... -0.02451991 -0.29477504
   0.09512035]
 ...
 [-0.6929802  -0.3816776  -0.16954614 ... -0.54828227 -0.22178961
   0.8018081 ]
 [-0.4157763  -0.32710147 -0.19066389 ... -0.6222933  -0.4254632
   0.67794114]
 [-0.6351339  -0.35842043  0.05096419 ... -0.6506854  -0.4093783
   0.61668533]]
(324, 10)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Output shape of the Dense layer: (1, 10)
Dense layer output saved


In [35]:
weights_and_biases = np.loadtxt("model_weights.txt")

weights_shape = (3, 3, 1, 4)  # Assuming kernel size of (3, 3) and 4 filters
weights2_shape = (3, 3, 4, 4)
weights3_shape = (324, 10)

weights = weights_and_biases[0:36].reshape(weights_shape)  # weights
biases = weights_and_biases[36:40]  # biases

weights2 = weights_and_biases[40:184].reshape(weights2_shape)
biases2 = weights_and_biases[184:188]

weights3 = weights_and_biases[188:3428].reshape(weights3_shape)
biases3 = weights_and_biases[3428:3438]

print(weights3)
print(weights3.shape)
print(weights3[0*81:,2])
print(weights3[1*81:,2])
print(weights3[2*81:,2])
print(weights3[3*81:,2])

#Model Below
model = Sequential()
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu', input_shape=(42, 42, 1)))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(4, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size = (2, 2)))
model.add(Flatten())
#model.add(Dense(10, activation='relu'))

model.layers[0].set_weights([weights, biases])
model.layers[2].set_weights([weights2, biases2])
#model.layers[5].set_weights([weights3, biases3])


img_path = 'demo7.png'  
img = image.load_img(img_path, target_size=(42, 42), color_mode='grayscale')  
img_array = image.img_to_array(img)
img_array = np.expand_dims(img_array, axis=0)
# img_array /= 255.  
img_flat = img_array.flatten()
img_array = np.array(img_flat)


img_array = img_flat.reshape((1, 42, 42, 1))  # Reshape to (batch_size, height, width, channels)

max2_output = model.predict(img_array)

print(max2_output)
# Save the convolutional layer output
print("Output shape of the Dense layer:", max2_output.shape)

# Save the dense layer output
#with open('Python_prog_out_Dense.txt', 'w') as file:
#    for i in range(conv1_output.shape[1]):
#        file.write("Neuron %d: %0.2f\n" % (i + 1, max2_output[0, i]))

#print("Dense layer output saved")


[[-0.0628828   0.08443162 -0.06693464 ... -0.16860108 -0.2712759
  -0.5382995 ]
 [-0.56143224  0.04709087 -0.01200746 ... -0.04370009 -0.51703787
   0.00160865]
 [-0.05777652  0.05571867 -0.13674326 ... -0.02451991 -0.29477504
   0.09512035]
 ...
 [-0.6929802  -0.3816776  -0.16954614 ... -0.54828227 -0.22178961
   0.8018081 ]
 [-0.4157763  -0.32710147 -0.19066389 ... -0.6222933  -0.4254632
   0.67794114]
 [-0.6351339  -0.35842043  0.05096419 ... -0.6506854  -0.4093783
   0.61668533]]
(324, 10)
[-6.69346400e-02 -1.20074630e-02 -1.36743260e-01 -1.06903460e-01
  3.94939800e-02  3.18853320e-01  1.57462330e-01  2.42653010e-01
  1.74437630e-01  5.01645500e-01  6.02862700e-01  4.03753820e-01
  7.97290800e-02  5.61858950e-01  6.43399500e-01  3.93291320e-01
  1.04357320e-01  4.62855850e-01  6.82405650e-01  3.19821600e-01
  8.16873240e-02  4.47457100e-01  5.41214470e-01  2.68627800e-01
 -7.71088300e-02  2.17887300e-01  2.86196170e-01  1.56687300e-02
 -2.58964900e-01 -2.19503800e-01 -2.26970900e-

c:\Users\Rishit Thakkar\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:99: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(


In [43]:
print(weights3[:,0])
print(weights3.shape)

[-0.0628828  -0.56143224 -0.05777652 -0.64277047 -0.27630126 -0.42569417
 -0.5058803  -0.35963646 -0.1291364  -0.18747672 -0.3822866  -0.21757637
 -0.02284618 -0.05292128 -0.19709247  0.0532147   0.11098424  0.24711229
 -0.14949729  0.29329622  0.10942538  0.2631237  -0.16586132  0.21083163
  0.05651291  0.20739934 -0.14853683  0.11621948  0.03766488 -0.08272779
 -0.26614848 -0.10072731  0.01199793 -0.5397823  -0.5534407  -0.4611396
 -0.1588125  -0.94191325 -0.56085294 -0.6822576  -0.22096969 -0.34391403
 -0.05221902 -0.3895572  -0.28058553 -0.20277134 -0.10204247 -0.09077868
 -0.11321877 -0.04481785 -0.04376646 -0.06871933  0.05159071  0.08951378
  0.03366006  0.11962752  0.16428761  0.20122069  0.15618005  0.15385604
  0.19331625  0.12807706  0.18847096  0.0253465   0.06075673  0.07465037
  0.19048187  0.02102919 -0.12028682  0.00505031 -0.25680864 -0.04713763
 -0.10192462 -0.54220045 -0.45827302 -0.52211756 -0.28032726 -0.1621164
 -0.07669959 -0.0978513  -0.14429691 -0.06501123 -0.0

In [44]:
print(max2_output)
print(max2_output.shape)

[[2.2493108e+03 1.4951920e+03 1.3288309e+03 1.8442101e+03 2.0124934e+04
  1.3302759e+04 1.1504303e+04 1.3058663e+04 3.7949051e+04 2.4192615e+04
  1.9092648e+04 2.4520775e+04 4.1693383e+04 2.6648846e+04 1.9842307e+04
  2.5344885e+04 2.9915912e+04 1.7962824e+04 1.1164329e+04 1.6691500e+04
  9.6580547e+03 5.0244790e+03 1.5640781e+03 4.6463911e+03 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 4.3595410e+03 3.0888894e+03 6.8479761e+03 7.7523926e+03
  4.2587438e+04 4.4559426e+04 7.1637734e+04 5.0149738e+04 6.1308055e+04
  6.5571359e+04 9.0126664e+04 5.7700629e+04 6.4228711e+04 7.0618742e+04
  9.2417883e+04 5.3778352e+04 6.4648344e+04 6.9864555e+04 8.3241414e+04
  5.4551957e+04 4.5820738e+04 4.6488867e+04 3.6153844e+04 2.8564721e+04
  7.0658237e+03 3.3298386e+03 2.7536261e+02 3.3179065e+03 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000

In [26]:
import numpy as np

In [32]:
print(np.matmul(max2_output, weights3) + biases3)

[[ -500694.41436946 -1309289.3143765   -201958.50022189   547047.20066867
   -839979.49999342     7207.10891517  -738034.48166799  -492147.15098327
     23648.22340149  -653783.05755579]]
